### ISSUE TITLE
Displaying images

### ISSUE THREAD

**Issue by StuMunsonMcGee** [alastairhm/micropython-st7735#1]
I got the program to display the tux.bmp file to work on my Pico using the ST7735 driver.  However, I can not get my own image to display.  I used GIMP to create a 126x160 images saved in bmp format.  After placing it in the same location as the TUX.BMP file, it would not display.  Does something else need to be done when creating the bmp file so it will display?  Thanks

Stu

**Comment by alastairhm** [comment]
Hi, I can't remember if it needs to be a specific format but will investigate.
Do you want to attach your test image?

**Comment by StuMunsonMcGee** [comment]
I found on another site that it needs to be stored in 24 bit format. That
took care of it. Thanks,

Stu

**Comment by alastairhm** [comment]
Thank you, I'll add that to the instructions.

**Comment by alastairhm** [comment]
Updated the README and example to include 24 bit info.
